coverage:
  status:
    project:
      default:
        paths:
          - "cmd"
          - "pkg"
        informational: true
    patch:
      default:
        paths:
          - "cmd"
          - "pkg"
        informational: true
ignore:
  - "**/*_mock.go"
  - "**/*_test.go"
  - "assets"
  - "hack"
  - "templates"
  - "tools"
  - "vendor"
